function dat = runCoupledModel(C,P) %,saScale,wScale,dD)
% dat = runCoupledModel(C,P)
% Wrapper function for a single run of couple conduit/vent/plume model
% C = user params for conduit. See getConduitSource for options.
% P = user params for MWI and plume. See getPlumeSource for options.
%      '-> Most of these are inherited from conduit/vent models and should
%          be input for C
%
% OUTPUT:
%   dat : struct containing substructs generated by each model component
%           cI = conduit model input        (getConduitSource.m)
%           cO = conduit model output       (Conduit_flow_with_nucleation_V6.m)
%           dO = vent decompression output  (getLd.m)
%           wO = magma-h20 model output     (MWIv1.m)
%           pI = plume model input          (getPlumeSource.m)
%           pO = plume model output         (hmodel.m)
%
% CRowell Mar 2021

if nargin<2
    P = [];
end
if nargin<1
    C = [];
end

addpath(genpath('./Hajimirza_Conduit/'))
addpath(genpath('./1Dplume_DB2012/'))
addpath(genpath('./vent/'))
addpath(genpath('./utils/'))
addpath(genpath('./plot-tools/'))

    % Crude (temp) MWI params
%     if nargin<5; dD = []; end
%     if nargin<4; wScale = []; end
%     if nargin<3; saScale = []; end
%     if isempty(saScale); saScale = 10; end
%     if isempty(wScale);  wScale  = 5; end
%     if isempty(dD);      dD      = 0.2; end

% Conduit run failure thresholds - should make conduit model input
ZfailScale  = 2;   % Z (depth) threshold in conduit radii
Mfailthresh = 0.95; % Mach number threshold
Pfailthresh = .05;  % Over-/underpressure threshold

%% Do the thing
    
    if isfield(C,'proxy') % Default setting: run full conduit model
        if islogical(C.proxy)
            proxyCon = C.proxy;
        else
            proxyCon = false;
        end
    else
        proxyCon = false;
    end
    
    if proxyCon
        
        [dat.cI,dat.cO,atmo]  = getProxyConduitSourceV2(C);
    else

        % Setup up conduit model
        if isempty(C)
            [dat.cI,atmo]  = getConduitSource;
        else
            [dat.cI,atmo]  = getConduitSource(C);
        end
        % Run Conduit
        dat.cO  = Conduit_flow_with_nucleation_V6(dat.cI);
        
        % Check conduit valid solution
        [~,~,~,~,~,dat.cO.Par.conValid] = checkConduitResult(dat.cO,dat.cI.conduit_radius*dat.cI.ZfailScale,dat.cI.Mfailthresh,dat.cI.Pfailthresh);
    %     toc
    end


    %% Vent
%     dat.plumeI  = con2plume(dat.conduitI,dat.conduitO,P);
    P.atmo      = atmo.atmo;
    P.atmoVars  = atmo.atmoVars;
    P.atmoUnits = atmo.atmoUnits;
    
    [dat.pI,dat.dO,dat.wO]  = con2plume(dat.cI,dat.cO,P); %,saScale,wScale,dD);

    %% Run plume?
    if dat.cO.Par.frag && ~dat.wO.failedPlume
        dat.pO  = hmodel(dat.pI,true);
    else
        dat.pO.hm = NaN;
        dat.pO.rm = NaN;
        dat.pO.hb = NaN;
        dat.pO.collapse = NaN;
        dat.pO.m_0 = NaN;
        dat.pO.P_0 = NaN;
        dat.pO.atmo.theta_a = atmo.atmo(:,3);
        dat.pO.atmo.ztropo = findTPheight(atmo.atmo(:,2)/1e3,atmo.atmo(:,3));
        dat.pO.atmo.zDatum = dat.cI.vh0;
    end
    
    
%% View output

% singleRunSummary(dat)     % Summary table
% plotCoupledPlume(dat)     % Plot output
end